apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Namespace
- apps/microservices-demo/base/namespace.yaml

# Microservices base
- apps/microservices-demo/base/frontend-deployment.yaml
- apps/microservices-demo/base/frontend-service.yaml
- apps/microservices-demo/base/api-deployment.yaml
- apps/microservices-demo/base/api-service.yaml
- apps/microservices-demo/base/cache-deployment.yaml
- apps/microservices-demo/base/cache-service.yaml

# NGINX vs Traefik comparison
- apps/nginx-comparison/app-v1.yaml
- apps/nginx-comparison/app-v2.yaml
- apps/nginx-comparison/service.yaml
- apps/nginx-comparison/ingresses.yaml

# Ingress
- ingress/ingress-class.yaml

# Istio
- istio/gateway.yaml

labels:
- pairs:
    managed-by: k8s-playground
  includeSelectors: true
