apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-canary-vsvc
  namespace: demo
spec:
  hosts:
  - api
  http:
  - name: primary
    route:
    - destination:
        host: api-stable
      weight: 100
    - destination:
        host: api-canary
      weight: 0
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: api-canary-dr
  namespace: demo
spec:
  host: api
  subsets:
  - name: stable
    labels:
      app: api
  - name: canary
    labels:
      app: api
