apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: demo
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
