apiVersion: v1
kind: Service
metadata:
  name: nginx-comparison
  namespace: demo
spec:
  selector:
    app: nginx-comparison
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
